---
kind: pipeline
type: kubernetes
name: build

services:
  - name: localstack
    image: quay.io/ukhomeofficedigital/localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: quay.io/ukhomeofficedigital/localstack # need curl which is not in alpine
    commands:
      - ./config/localstack/setup-sqs.sh
    depends_on:
      - clone

  - name: build project
    image: quay.io/ukhomeofficedigital/openjdk11:v11.0.5_10
    commands:
      - ./gradlew assemble --no-daemon
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/openjdk11:v11.0.5_10
    environment:
      LOCALSTACK_HOST: "localstack"
    commands:
      - ./gradlew check --no-daemon
    depends_on:
      - setup localstack
      - build project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-queue-tool
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        exclude:
          - main
    depends_on:
      - test project

  - name: build & push latest
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-queue-tool
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        include:
          - main
    depends_on:
      - test project

trigger:
  event:
    - push
