---
kind: pipeline
type: kubernetes
name: validate k8
trigger:
  event:
    - push
  branch:
    exclude:
      - main

steps:
  - name: lint bash
    image: koalaman/shellcheck-alpine
    commands:
      - shellcheck kube/*.sh
    depends_on:
      - clone

  - name: dry-run kd dev
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      DRY_RUN: true
      VERSION: test
      ENVIRONMENT: cs-dev
      KUBE_TOKEN: test
      KUBE_SERVER: test
      CLUSTER_NAME: test
    commands:
      - cd kube
      - bash -x deploy.sh
    depends_on:
      - lint bash

  - name: dry-run kd prod
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      DRY_RUN: true
      VERSION: test
      ENVIRONMENT: cs-prod
      KUBE_TOKEN: test
      KUBE_SERVER: test
      CLUSTER_NAME: test
    commands:
      - cd kube
      - bash -x deploy.sh
    depends_on:
      - lint bash
