audit-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/audit-queue

audit-dlq:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/audit-queue-dlq

case-creator-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/case-creator-queue

case-creator-dlq:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/case-creator-queue-dlq

document-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/document-queue

document-dlq:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/document-queue-dlq

migration-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/migration-queue

notify-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/notify-queue

notify-dlq:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/notify-queue-dlq

search-queue:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/search-queue

search-dlq:
  endpoint: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/search-queue-dlq
