spring:
  main:
    banner-mode: off

server:
  shutdown: graceful
  http2:
    enabled: true
  port: 8094

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

sqs-region: eu-west-2
