sqs-provider: aws
sqs-region: eu-west-2

search-queue:
  sqs-queue: ${search.queue:false}
  access-key-id: ${search.queue.access.key.id:UNSET}
  secret-access-key: ${search.queue.secret.access.key:UNSET}

search-dlq:
  sqs-queue: ${search.dlq.queue:false}
  access-key-id: ${search.dlq.access.key.id:UNSET}
  secret-access-key: ${search.dlq.secret.access.key:UNSET}

audit-queue:
  sqs-queue: ${audit.queue:false}
  access-key-id: ${audit.queue.access.key.id:UNSET}
  secret-access-key: ${audit.queue.secret.access.key:UNSET}

audit-dlq:
  sqs-queue: ${audit.dlq.queue:false}
  access-key-id: ${audit.dlq.access.key.id:UNSET}
  secret-access-key: ${audit.dlq.secret.access.key:UNSET}

document-queue:
  sqs-queue: ${document.queue:false}
  access-key-id: ${document.queue.access.key.id:UNSET}
  secret-access-key: ${document.queue.secret.access.key:UNSET}

document-dlq:
  sqs-queue: ${document.dlq.queue:false}
  access-key-id: ${document.dlq.access.key.id:UNSET}
  secret-access-key: ${document.dlq.secret.access.key:UNSET}

notify-queue:
  sqs-queue: ${notify.queue:false}
  access-key-id: ${notify.queue.access.key.id:UNSET}
  secret-access-key: ${notify.queue.secret.access.key:UNSET}

notify-dlq:
  sqs-queue: ${notify.dlq.queue:false}
  access-key-id: ${notify.dlq.access.key.id:UNSET}
  secret-access-key: ${notify.dlq.secret.access.key:UNSET}

case-creator-queue:
  sqs-queue: ${case.creator.queue:false}
  access-key-id: ${case.creator.queue.access.key.id:UNSET}
  secret-access-key: ${case.creator.queue.secret.access.key:UNSET}

case-creator-dlq:
  sqs-queue: ${case.creator.dlq.queue:false}
  access-key-id: ${case.creator.dlq.access.key.id:UNSET}
  secret-access-key: ${case.creator.dlq.secret.access.key:UNSET}

migration-queue:
  sqs-queue: ${migration.queue:false}
  access-key-id: ${migration.queue.access.key.id:UNSET}
  secret-access-key: ${migration.queue.secret.access.key:UNSET}
