apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hocs-app.name" . }}
  labels:
    version: {{ .Values.version }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.minReplicas }}
  selector:
    matchLabels:
      name: {{ include "hocs-app.name" . }}
  template:
    metadata:
      labels:
        {{- include "hocs-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "hocs-app.name" . }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.version }}"
          securityContext:
            {{- include "hocs-app.securityContext" . | nindent 12 }}
          env:
            {{ include "deployment.envs" . | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.app.port }}
          {{ include "healthcheck.envs" . | nindent 10 }}
          lifecycle:
            preStop:
              exec:
                command: {{ .Values.app.preStop }}
