---
hocs-generic-service:
  nameOverride: hocs-queue-tool

  autoscale:
    enabled: false

  service:
    enabled: false

  deployment:
    replicas: 1
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-04:55 Europe/London,Mon-Sun 23:05-24:00 Europe/London"

  truststore:
    enabled: false

  proxy:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-queue-tool
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'aws'
      queues:
        - 'audit'
        - 'case-creator'
        - 'document'
        - 'notify'
        - 'search'
        - 'extracts'
      migrationQueueEnabled: 'false'
