---
nameOverride: hocs-queue-tool

minReplicas: 1

deploymentAnnotations:
  downscaler/downtime: "Mon-Sun 00:00-04:55 Europe/London,Mon-Sun 23:05-24:00 Europe/London"
service:
  portName: "http"

app:
  image:
    repository: quay.io/ukhomeofficedigital/hocs-queue-tool
  selectorRole: hocs-backend
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  javaOpts: >-
    -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
    -Djava.security.egd=file:/dev/./urandom
    -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
    -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
    -Dhttps.proxyPort=31290
    -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
  springProfiles: 'aws'
  port: 8080
  queues:
    - 'audit'
    - 'case-creator'
    - 'document'
    - 'notify'
    - 'search'
    - 'extracts'
  migrationQueueEnabled: 'false'
  preStop: '[ "sh", "-c", "sleep 20" ]'
