---
hocs-generic-service:

  deployment:
    annotations:
      downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-07:55 Europe/London,Mon-Fri 18:05-24:00 Europe/London"

  app:
    env:
      queues:
        - 'audit'
        - 'case-creator'
        - 'case-migrator'
        - 'document'
        - 'notify'
        - 'opensearch'
