---
hocs-generic-service:

  app:
    env:
      queues:
        - 'audit'
        - 'case-creator'
        - 'document'
        - 'notify'
        - 'search'
        - 'extracts'
        - 'case-migrator'
      migrationQueueEnabled: 'true'
